###
GET  http://localhost:8000/user/2


###
GET  http://localhost:8000/users

###
POST  http://localhost:8000/create-student
Content-Type: application/json

{
  "firstname": "Tiffany",
  "lastname": "Perkins",
  "username": "Perky",
  "password": "password",
  "email": "perkyperk@gmail.com",
  "contact": "123-456-7890",
  "school": "University of Texas",
  "role": "student"
}

###
POST  http://localhost:8000/auth/login
Content-Type: application/json

{
  "username": "Perky",
  "password": "password"
}

