###
GET  http://localhost:8000/user/2


###
GET  http://localhost:8000/users

###
POST  http://localhost:8000/create-student
Content-Type: application/json

{
  "firstname": "Tiffany",
  "lastname": "Perkins",
  "username": "Perky",
  "password": "password",
  "email": "perkyperk@gmail.com",
  "contact": "123-456-7890",
  "school": "University of Texas",
  "role": "student"
}

###
POST  http://localhost:8000/auth/login
Content-Type: application/json

{
  "username": "Perky",
  "password": "password"
}

###  
POST http://localhost:8000/create-career
Content-Type: application/json

  {
    "career_name": "Software Engineer",
    "description": "Design, develop, and maintain software systems and applications.",
    "requirements": "Bachelor's in Computer Science or related field",
    "subjects": "Mathematics, Computer Studies, Physics",
    "interests": "Programming, Problem-solving, AI",
    "image": "https://thumbs.dreamstime.com/z/career-concept-technology-light-background-blurred-abstract-168248861.jpg"
  }

###
GET  http://localhost:8000/all-careers

###
POST http://localhost:8000/create-feedback
Content-Type: application/json

{
  "name": "Tiffany Perkins",
  "email": "tiffperks@gmail.com",
  "message": "I love this career!",
  "contact": "123-456-7890"
}

###
GET  http://localhost:8000/students
###
DELETE   http://localhost:8000/delete-student/1

###
POST http://localhost:8000/create-personal-intrest
Content-Type: application/json

{
  "student_id": 11,
  "personal_interests": "Skating, poetry, Anime"
}

###
DELETE  http://localhost:8000/delete-personal-intrest/5

###
POST http://localhost:8000/create-recommendations
Content-Type: application/json

{
  "student_id": 1,
  "student_recommendations": ' "Bachelor of Science (Applied Bioengineering), Bachelor of Technology in Medical Engineering, Bachelor of Science (Biomedical Engineering)","Bachelor of Science in Applied Bioengineering"',
}

###
POST http://localhost:8000/create-recommendations
Content-Type: application/json

{
    "student_id": 1,
    "student_recommendations": [
      "Bachelor of Science in Food Service and Hospitality Management",
      "Bachelor of Arts (Translation and Interpretation)",
      "Bachelor of Arts (Theatre Arts & Film Technology)",
      "Bachelor of Science (Food Operations Management)",
      "Bachelor of Arts (Literature)"
    ]
  }

###
GET http://localhost:8000/get-students-career-interests/1
###
GET http://localhost:8000/get-student-academics/1

###
GET http://localhost:8000/student-history/1


###
POST http://localhost:8000/create-academic
Content-Type: application/json

{
  "student_id": 1,
  "subject_id": 4,
  "grade": "A",
}

###
POST http://localhost:8000/create-subject
Content-Type: application/json

{
  "subject_name": "Home science"
}

###
GET http://localhost:8000/get-student-recommendations/1

###
GET http://localhost:8000/get-recommendation-attributes/1